version: '3.8'

services:
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sonastik_ee_migrate
    entrypoint: >
      sh -c "
        echo 'Waiting for database to be ready...'
        while ! pg_isready -h db -p 5432 -U postgres; do
          sleep 1
        done
        echo 'Database is ready, running migrations...'
        /app/bin/sonastik_ee eval 'SonastikEe.Release.migrate()'
      "
    environment:
      - DATABASE_URL=ecto://${DB_USER}:${DB_PASSWORD}@db:5432/sonastik_ee_prod
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_USER=${DB_USER:-postgres}
      - DB_NAME=${DB_NAME:-sonastik_ee_prod}
    networks:
      - sonastik_network
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sonastik_ee_web
    restart: always
    ports:
      - "${PORT:-4000}:4000"
    environment:
      - PHX_HOST=${PHX_HOST:-localhost}
      - PORT=${PORT:-4000}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DATABASE_URL=${DATABASE_URL}
      - POOL_SIZE=${POOL_SIZE:-10}
      - DEEPL_API_KEY=${DEEPL_API_KEY}
      - DNS_CLUSTER_QUERY=${DNS_CLUSTER_QUERY}
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - sonastik_network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  db:
    image: postgres:16-alpine
    container_name: sonastik_ee_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_DB=${DB_NAME:-sonastik_ee_prod}
    volumes:
      - sonastik_db_data:/var/lib/postgresql/data
    networks:
      - sonastik_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-sonastik_ee_prod}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  sonastik_network:
    driver: bridge

volumes:
  sonastik_db_data:
